/* =====================================================================
 * dtcdb.js — Bază de date descrieri coduri de eroare (RO)
 *   Generice SAE J2012 (P0/P2/U0) + specifice Ford (P1/B/C/U) frecvente 2007–2010.
 *   Codurile P1xxx/Bxxxx/Cxxxx/U1-3xxx sunt definite de producător:
 *   descrierea poate diferi între modele — verificați manualul de service Ford.
 * ===================================================================== */
'use strict';

const DTC_DB = {
  /* ---------- Măsurare aer și combustibil ---------- */
  P0010: 'Actuator ax came admisie (VCT) – circuit, bancul 1', P0011: 'Ax came admisie – sincronizare prea avansată, bancul 1',
  P0012: 'Ax came admisie – sincronizare prea întârziată, bancul 1', P0013: 'Actuator ax came evacuare – circuit, bancul 1',
  P0014: 'Ax came evacuare – sincronizare prea avansată, bancul 1', P0016: 'Corelație arbore cotit / ax came (bancul 1, senzor A)',
  P0017: 'Corelație arbore cotit / ax came (bancul 1, senzor B)', P0020: 'Actuator ax came admisie – circuit, bancul 2',
  P0030: 'Încălzire sondă O2 – circuit control (B1S1)', P0031: 'Încălzire sondă O2 – circuit nivel scăzut (B1S1)',
  P0032: 'Încălzire sondă O2 – circuit nivel ridicat (B1S1)', P0036: 'Încălzire sondă O2 – circuit control (B1S2)',
  P0037: 'Încălzire sondă O2 – nivel scăzut (B1S2)', P0038: 'Încălzire sondă O2 – nivel ridicat (B1S2)',
  P0040: 'Semnale sonde O2 inversate (B1S1/B2S1)', P0045: 'Turbo – solenoid control presiune, circuit deschis',
  P0046: 'Turbo – solenoid control presiune, domeniu/performanță', P0050: 'Încălzire sondă O2 – circuit control (B2S1)',
  P0068: 'Corelație MAP/MAF – poziție clapetă', P0069: 'Corelație MAP – presiune barometrică',
  P0087: 'Presiune rampă combustibil prea mică', P0088: 'Presiune rampă combustibil prea mare',
  P0089: 'Regulator presiune combustibil – performanță', P0090: 'Regulator presiune combustibil – circuit control',
  P0093: 'Scurgere sistem combustibil detectată (scurgere mare)', P0095: 'Senzor temperatură aer admisie 2 – circuit',
  P0100: 'Debitmetru aer (MAF) – circuit', P0101: 'Debitmetru aer (MAF) – domeniu/performanță',
  P0102: 'Debitmetru aer (MAF) – semnal scăzut', P0103: 'Debitmetru aer (MAF) – semnal ridicat',
  P0104: 'Debitmetru aer (MAF) – circuit intermitent', P0105: 'Senzor MAP/baro – circuit',
  P0106: 'Senzor MAP/baro – domeniu/performanță', P0107: 'Senzor MAP/baro – semnal scăzut',
  P0108: 'Senzor MAP/baro – semnal ridicat', P0110: 'Senzor temperatură aer admisie (IAT) – circuit',
  P0111: 'Senzor IAT – domeniu/performanță', P0112: 'Senzor IAT – semnal scăzut', P0113: 'Senzor IAT – semnal ridicat',
  P0115: 'Senzor temperatură lichid răcire (ECT) – circuit', P0116: 'Senzor ECT – domeniu/performanță',
  P0117: 'Senzor ECT – semnal scăzut', P0118: 'Senzor ECT – semnal ridicat', P0119: 'Senzor ECT – circuit intermitent',
  P0120: 'Senzor poziție clapetă/pedală A – circuit', P0121: 'Senzor poziție clapetă A – domeniu/performanță',
  P0122: 'Senzor poziție clapetă A – semnal scăzut', P0123: 'Senzor poziție clapetă A – semnal ridicat',
  P0125: 'Temperatură lichid răcire insuficientă pentru buclă închisă', P0128: 'Termostat – temperatură sub pragul de reglare (termostat blocat deschis)',
  P0130: 'Sondă O2 B1S1 – circuit', P0131: 'Sondă O2 B1S1 – tensiune scăzută', P0132: 'Sondă O2 B1S1 – tensiune ridicată',
  P0133: 'Sondă O2 B1S1 – răspuns lent', P0134: 'Sondă O2 B1S1 – fără activitate', P0135: 'Încălzire sondă O2 B1S1 – circuit',
  P0136: 'Sondă O2 B1S2 – circuit', P0137: 'Sondă O2 B1S2 – tensiune scăzută', P0138: 'Sondă O2 B1S2 – tensiune ridicată',
  P0139: 'Sondă O2 B1S2 – răspuns lent', P0140: 'Sondă O2 B1S2 – fără activitate', P0141: 'Încălzire sondă O2 B1S2 – circuit',
  P0150: 'Sondă O2 B2S1 – circuit', P0151: 'Sondă O2 B2S1 – tensiune scăzută', P0152: 'Sondă O2 B2S1 – tensiune ridicată',
  P0153: 'Sondă O2 B2S1 – răspuns lent', P0155: 'Încălzire sondă O2 B2S1 – circuit', P0156: 'Sondă O2 B2S2 – circuit',
  P0161: 'Încălzire sondă O2 B2S2 – circuit',
  P0170: 'Corecție amestec – bancul 1', P0171: 'Amestec prea sărac – bancul 1', P0172: 'Amestec prea bogat – bancul 1',
  P0173: 'Corecție amestec – bancul 2', P0174: 'Amestec prea sărac – bancul 2', P0175: 'Amestec prea bogat – bancul 2',
  P0180: 'Senzor temperatură combustibil A – circuit', P0181: 'Senzor temperatură combustibil A – domeniu/performanță',
  P0190: 'Senzor presiune rampă combustibil – circuit', P0191: 'Senzor presiune rampă – domeniu/performanță',
  P0192: 'Senzor presiune rampă – semnal scăzut', P0193: 'Senzor presiune rampă – semnal ridicat',
  P0196: 'Senzor temperatură ulei motor – domeniu/performanță', P0197: 'Senzor temperatură ulei – semnal scăzut',
  P0198: 'Senzor temperatură ulei – semnal ridicat',
  P0200: 'Injectoare – circuit', P0201: 'Injector cilindru 1 – circuit', P0202: 'Injector cilindru 2 – circuit',
  P0203: 'Injector cilindru 3 – circuit', P0204: 'Injector cilindru 4 – circuit', P0205: 'Injector cilindru 5 – circuit',
  P0206: 'Injector cilindru 6 – circuit', P0207: 'Injector cilindru 7 – circuit', P0208: 'Injector cilindru 8 – circuit',
  P0217: 'Supraîncălzire motor', P0218: 'Supraîncălzire transmisie', P0219: 'Turație maximă motor depășită',
  P0220: 'Senzor poziție clapetă/pedală B – circuit', P0221: 'Senzor poziție clapetă B – domeniu/performanță',
  P0222: 'Senzor poziție clapetă B – semnal scăzut', P0223: 'Senzor poziție clapetă B – semnal ridicat',
  P0230: 'Pompă combustibil – circuit primar', P0231: 'Pompă combustibil – circuit secundar scăzut',
  P0232: 'Pompă combustibil – circuit secundar ridicat', P0234: 'Supraalimentare turbo excesivă (overboost)',
  P0235: 'Senzor presiune turbo A – circuit', P0236: 'Senzor presiune turbo A – domeniu/performanță',
  P0237: 'Senzor presiune turbo A – semnal scăzut', P0238: 'Senzor presiune turbo A – semnal ridicat',
  P0243: 'Solenoid wastegate turbo A – circuit', P0245: 'Solenoid wastegate A – semnal scăzut', P0246: 'Solenoid wastegate A – semnal ridicat',
  P0251: 'Pompă injecție A (camă/rotor) – defect', P0261: 'Injector cil. 1 – circuit scăzut', P0262: 'Injector cil. 1 – circuit ridicat',
  P0263: 'Cilindru 1 – contribuție/echilibrare', P0264: 'Injector cil. 2 – circuit scăzut', P0265: 'Injector cil. 2 – circuit ridicat',
  P0266: 'Cilindru 2 – contribuție/echilibrare', P0267: 'Injector cil. 3 – circuit scăzut', P0268: 'Injector cil. 3 – circuit ridicat',
  P0269: 'Cilindru 3 – contribuție/echilibrare', P0270: 'Injector cil. 4 – circuit scăzut', P0271: 'Injector cil. 4 – circuit ridicat',
  P0272: 'Cilindru 4 – contribuție/echilibrare', P0299: 'Presiune turbo insuficientă (underboost)',
  /* ---------- Aprindere / rateuri ---------- */
  P0300: 'Rateuri aleatorii / multiple detectate', P0301: 'Rateuri cilindru 1', P0302: 'Rateuri cilindru 2',
  P0303: 'Rateuri cilindru 3', P0304: 'Rateuri cilindru 4', P0305: 'Rateuri cilindru 5', P0306: 'Rateuri cilindru 6',
  P0307: 'Rateuri cilindru 7', P0308: 'Rateuri cilindru 8', P0315: 'Variație poziție arbore cotit neînvățată',
  P0316: 'Rateuri detectate la pornire (primele 1000 rotații)', P0320: 'Senzor turație/poziție aprindere – circuit',
  P0325: 'Senzor detonație 1 – circuit (bancul 1)', P0326: 'Senzor detonație 1 – domeniu/performanță',
  P0327: 'Senzor detonație 1 – semnal scăzut', P0328: 'Senzor detonație 1 – semnal ridicat', P0330: 'Senzor detonație 2 – circuit (bancul 2)',
  P0335: 'Senzor poziție arbore cotit (CKP) A – circuit', P0336: 'Senzor CKP A – domeniu/performanță',
  P0337: 'Senzor CKP A – semnal scăzut', P0338: 'Senzor CKP A – semnal ridicat', P0339: 'Senzor CKP A – intermitent',
  P0340: 'Senzor poziție ax came (CMP) A – circuit (bancul 1)', P0341: 'Senzor CMP A – domeniu/performanță',
  P0342: 'Senzor CMP A – semnal scăzut', P0343: 'Senzor CMP A – semnal ridicat', P0344: 'Senzor CMP A – intermitent',
  P0345: 'Senzor CMP A – circuit (bancul 2)', P0350: 'Bobine aprindere – circuit primar/secundar',
  P0351: 'Bobină aprindere A – circuit primar/secundar', P0352: 'Bobină aprindere B – circuit', P0353: 'Bobină aprindere C – circuit',
  P0354: 'Bobină aprindere D – circuit', P0355: 'Bobină aprindere E – circuit', P0356: 'Bobină aprindere F – circuit',
  P0365: 'Senzor ax came B – circuit (bancul 1)', P0366: 'Senzor ax came B – domeniu/performanță',
  P0380: 'Bujii incandescente – circuit A', P0381: 'Lampă avertizare bujii incandescente – circuit', P0382: 'Bujii incandescente – circuit B',
  /* ---------- Control emisii ---------- */
  P0400: 'Recirculare gaze (EGR) – debit', P0401: 'EGR – debit insuficient', P0402: 'EGR – debit excesiv',
  P0403: 'EGR – circuit control', P0404: 'EGR – domeniu/performanță', P0405: 'Senzor poziție EGR A – semnal scăzut',
  P0406: 'Senzor poziție EGR A – semnal ridicat', P0409: 'Senzor EGR A – circuit', P0410: 'Sistem aer secundar',
  P0411: 'Aer secundar – debit incorect', P0412: 'Supapă comutare aer secundar A – circuit',
  P0420: 'Eficiență catalizator sub prag – bancul 1', P0421: 'Eficiență catalizator încălzit sub prag – bancul 1',
  P0430: 'Eficiență catalizator sub prag – bancul 2', P0440: 'Sistem emisii evaporative (EVAP)',
  P0441: 'EVAP – debit purjare incorect', P0442: 'EVAP – scurgere mică detectată', P0443: 'Supapă purjare EVAP – circuit',
  P0444: 'Supapă purjare EVAP – circuit deschis', P0445: 'Supapă purjare EVAP – scurtcircuit', P0446: 'Supapă aerisire EVAP – circuit control',
  P0447: 'Supapă aerisire EVAP – circuit deschis', P0448: 'Supapă aerisire EVAP – scurtcircuit',
  P0451: 'Senzor presiune EVAP – domeniu/performanță', P0452: 'Senzor presiune EVAP – semnal scăzut', P0453: 'Senzor presiune EVAP – semnal ridicat',
  P0455: 'EVAP – scurgere mare detectată (verificați bușonul rezervorului)', P0456: 'EVAP – scurgere foarte mică detectată',
  P0457: 'EVAP – scurgere (bușon rezervor slăbit/lipsă)', P0460: 'Senzor nivel combustibil – circuit',
  P0461: 'Senzor nivel combustibil – domeniu/performanță', P0462: 'Senzor nivel combustibil – semnal scăzut', P0463: 'Senzor nivel combustibil – semnal ridicat',
  P0470: 'Senzor presiune gaze evacuare – circuit', P0471: 'Senzor presiune gaze evacuare – domeniu/performanță',
  P0472: 'Senzor presiune gaze evacuare – semnal scăzut', P0473: 'Senzor presiune gaze evacuare – semnal ridicat',
  P0480: 'Ventilator răcire 1 – circuit control', P0481: 'Ventilator răcire 2 – circuit control',
  P0491: 'Aer secundar – bancul 1', P0496: 'EVAP – debit ridicat în afara purjării', P0497: 'EVAP – debit scăzut la purjare',
  /* ---------- Viteză / ralanti / intrări ---------- */
  P0500: 'Senzor viteză vehicul (VSS) A', P0501: 'Senzor VSS A – domeniu/performanță', P0503: 'Senzor VSS A – intermitent/neregulat',
  P0505: 'Sistem control ralanti (IAC)', P0506: 'Ralanti – turație sub valoarea așteptată', P0507: 'Ralanti – turație peste valoarea așteptată',
  P0511: 'Supapă aer ralanti – circuit', P0512: 'Circuit cerere demaror', P0513: 'Cheie imobilizator invalidă',
  P0520: 'Senzor/comutator presiune ulei – circuit', P0521: 'Senzor presiune ulei – domeniu/performanță',
  P0522: 'Senzor presiune ulei – semnal scăzut', P0523: 'Senzor presiune ulei – semnal ridicat', P0524: 'Presiune ulei motor prea mică',
  P0530: 'Senzor presiune agent frigorific A/C – circuit', P0532: 'Senzor presiune A/C – semnal scăzut', P0533: 'Senzor presiune A/C – semnal ridicat',
  P0540: 'Încălzitor aer admisie A – circuit', P0555: 'Senzor presiune servofrână – circuit',
  P0560: 'Tensiune sistem', P0562: 'Tensiune sistem scăzută', P0563: 'Tensiune sistem ridicată',
  P0564: 'Cruise control – semnal multifuncțional A', P0571: 'Comutator frână A – circuit (cruise)', P0572: 'Comutator frână A – semnal scăzut',
  P0573: 'Comutator frână A – semnal ridicat', P0579: 'Cruise control – semnal multifuncțional A domeniu/performanță',
  P0581: 'Cruise control – semnal multifuncțional A ridicat',
  /* ---------- Computer / ieșiri ---------- */
  P0600: 'Legătură comunicație serială', P0601: 'Modul control intern – eroare checksum memorie',
  P0602: 'Modul control – eroare programare', P0603: 'Modul control intern – eroare memorie KAM',
  P0604: 'Modul control intern – eroare RAM', P0605: 'Modul control intern – eroare ROM', P0606: 'Procesor modul control – defect',
  P0607: 'Modul control – performanță', P0610: 'Modul control – opțiuni vehicul', P0615: 'Releu demaror – circuit',
  P0620: 'Alternator – circuit control', P0622: 'Alternator – circuit câmp (F)', P0625: 'Alternator – terminal câmp scăzut',
  P0626: 'Alternator – terminal câmp ridicat', P0627: 'Pompă combustibil – circuit control deschis',
  P0628: 'Pompă combustibil – circuit control scăzut', P0629: 'Pompă combustibil – circuit control ridicat',
  P0630: 'VIN neprogramat sau incompatibil – ECM/PCM', P0638: 'Actuator clapetă – domeniu/performanță (bancul 1)',
  P0641: 'Tensiune referință senzori A – circuit deschis', P0642: 'Tensiune referință senzori A – scăzută',
  P0643: 'Tensiune referință senzori A – ridicată', P0645: 'Releu ambreiaj compresor A/C – circuit',
  P0650: 'Lampă MIL – circuit', P0651: 'Tensiune referință senzori B – circuit deschis', P0652: 'Referință senzori B – scăzută',
  P0653: 'Referință senzori B – ridicată', P0657: 'Tensiune alimentare actuatori A – circuit deschis',
  P0660: 'Supapă reglaj galerie admisie (IMRC/IMTV) – circuit, bancul 1', P0661: 'Supapă galerie admisie – circuit scăzut',
  P0662: 'Supapă galerie admisie – circuit ridicat', P0670: 'Modul control bujii incandescente – circuit',
  P0671: 'Bujie incandescentă cilindru 1 – circuit', P0672: 'Bujie incandescentă cilindru 2 – circuit',
  P0673: 'Bujie incandescentă cilindru 3 – circuit', P0674: 'Bujie incandescentă cilindru 4 – circuit',
  P0683: 'Comunicație modul bujii incandescente – PCM', P0685: 'Releu alimentare ECM/PCM – circuit deschis',
  P0686: 'Releu alimentare ECM/PCM – circuit scăzut', P0689: 'Releu alimentare ECM/PCM – circuit sens scăzut',
  P0690: 'Releu alimentare ECM/PCM – circuit sens ridicat', P0691: 'Ventilator răcire 1 – circuit scăzut', P0692: 'Ventilator răcire 1 – circuit ridicat',
  P0693: 'Ventilator răcire 2 – circuit scăzut', P0694: 'Ventilator răcire 2 – circuit ridicat',
  /* ---------- Transmisie ---------- */
  P0700: 'Sistem control transmisie – cerere MIL (citiți TCM)', P0702: 'Sistem control transmisie – electric',
  P0705: 'Senzor domeniu transmisie (TR) – circuit (PRNDL)', P0706: 'Senzor TR – domeniu/performanță',
  P0707: 'Senzor TR – semnal scăzut', P0708: 'Senzor TR – semnal ridicat', P0710: 'Senzor temperatură ulei transmisie (TFT) – circuit',
  P0711: 'Senzor TFT – domeniu/performanță', P0712: 'Senzor TFT – semnal scăzut', P0713: 'Senzor TFT – semnal ridicat',
  P0715: 'Senzor turație intrare/turbină (ISS) – circuit', P0716: 'Senzor ISS – domeniu/performanță', P0717: 'Senzor ISS – fără semnal',
  P0718: 'Senzor ISS – intermitent', P0720: 'Senzor turație ieșire (OSS) – circuit', P0721: 'Senzor OSS – domeniu/performanță',
  P0722: 'Senzor OSS – fără semnal', P0725: 'Intrare turație motor – circuit (TCM)', P0729: 'Treapta 6 – raport incorect',
  P0730: 'Raport transmisie incorect', P0731: 'Treapta 1 – raport incorect', P0732: 'Treapta 2 – raport incorect',
  P0733: 'Treapta 3 – raport incorect', P0734: 'Treapta 4 – raport incorect', P0735: 'Treapta 5 – raport incorect',
  P0736: 'Marșarier – raport incorect', P0740: 'Ambreiaj convertizor cuplu (TCC) – circuit', P0741: 'TCC – performanță / blocat decuplat',
  P0742: 'TCC – blocat cuplat', P0743: 'Solenoid TCC – electric', P0745: 'Solenoid control presiune A (EPC) – circuit',
  P0746: 'Solenoid presiune A – performanță / blocat', P0748: 'Solenoid presiune A – electric', P0750: 'Solenoid schimbare A – circuit',
  P0751: 'Solenoid schimbare A – performanță', P0753: 'Solenoid schimbare A – electric', P0755: 'Solenoid schimbare B – circuit',
  P0756: 'Solenoid schimbare B – performanță', P0758: 'Solenoid schimbare B – electric', P0760: 'Solenoid schimbare C – circuit',
  P0761: 'Solenoid schimbare C – performanță', P0763: 'Solenoid schimbare C – electric', P0765: 'Solenoid schimbare D – circuit',
  P0770: 'Solenoid schimbare E – circuit', P0780: 'Defect schimbare trepte', P0781: 'Schimbare 1-2 defectă', P0782: 'Schimbare 2-3 defectă',
  P0783: 'Schimbare 3-4 defectă', P0784: 'Schimbare 4-5 defectă', P0791: 'Senzor turație arbore intermediar – circuit',
  P0797: 'Solenoid control presiune C – blocat', P0841: 'Senzor presiune ulei transmisie A – domeniu/performanță',
  P0868: 'Presiune ulei transmisie scăzută', P0882: 'Tensiune alimentare TCM scăzută', P0883: 'Tensiune alimentare TCM ridicată',
  P0900: 'Actuator ambreiaj – circuit deschis (Powershift)', P0902: 'Actuator ambreiaj – circuit scăzut',
  /* ---------- P2xxx generice ---------- */
  P2002: 'Eficiență filtru particule (DPF) sub prag – bancul 1', P2004: 'Clapete galerie admisie (IMRC) blocate deschis – bancul 1',
  P2006: 'Clapete galerie admisie blocate închis – bancul 1', P2008: 'Clapete galerie admisie – circuit deschis',
  P2009: 'Clapete galerie admisie – circuit scăzut', P2014: 'Senzor poziție clapete galerie admisie – circuit',
  P2032: 'Senzor temperatură gaze evacuare B1S2 – semnal scăzut', P2033: 'Senzor temperatură gaze evacuare B1S2 – semnal ridicat',
  P2080: 'Senzor temperatură gaze evacuare B1S1 – domeniu/performanță', P2084: 'Senzor temperatură gaze evacuare B1S2 – domeniu/performanță',
  P2096: 'Corecție post-catalizator – prea sărac, bancul 1', P2097: 'Corecție post-catalizator – prea bogat, bancul 1',
  P2100: 'Motor actuator clapetă – circuit deschis', P2101: 'Motor actuator clapetă – domeniu/performanță',
  P2104: 'Sistem control clapetă – ralanti forțat (mod avarie)', P2105: 'Sistem control clapetă – motor oprit forțat',
  P2106: 'Sistem control clapetă – putere limitată forțat', P2107: 'Procesor modul control clapetă – defect',
  P2110: 'Sistem control clapetă – turație limitată forțat', P2111: 'Actuator clapetă – blocat deschis',
  P2112: 'Actuator clapetă – blocat închis', P2119: 'Corp clapetă actuator – domeniu/performanță',
  P2122: 'Senzor poziție pedală D – semnal scăzut', P2123: 'Senzor poziție pedală D – semnal ridicat',
  P2127: 'Senzor poziție pedală E – semnal scăzut', P2128: 'Senzor poziție pedală E – semnal ridicat',
  P2135: 'Corelație senzori poziție clapetă A/B', P2138: 'Corelație senzori poziție pedală D/E',
  P2146: 'Alimentare injectoare grup A – circuit deschis', P2149: 'Alimentare injectoare grup B – circuit deschis',
  P2177: 'Amestec prea sărac în afara ralantiului – bancul 1', P2178: 'Amestec prea bogat în afara ralantiului – bancul 1',
  P2187: 'Amestec prea sărac la ralanti – bancul 1', P2188: 'Amestec prea bogat la ralanti – bancul 1',
  P2195: 'Sondă O2 B1S1 – semnal blocat sărac', P2196: 'Sondă O2 B1S1 – semnal blocat bogat',
  P2197: 'Sondă O2 B2S1 – semnal blocat sărac', P2198: 'Sondă O2 B2S1 – semnal blocat bogat',
  P2227: 'Senzor presiune barometrică – domeniu/performanță', P2228: 'Senzor baro – semnal scăzut', P2229: 'Senzor baro – semnal ridicat',
  P2237: 'Sondă O2 B1S1 – circuit pozitiv curent pompare deschis', P2243: 'Sondă O2 B1S1 – tensiune referință deschisă',
  P2251: 'Sondă O2 B1S1 – circuit negativ deschis', P2263: 'Sistem turbo/supraalimentare – performanță',
  P2264: 'Senzor apă în combustibil – circuit', P2269: 'Apă în combustibil detectată',
  P2270: 'Sondă O2 B1S2 – semnal blocat sărac', P2271: 'Sondă O2 B1S2 – semnal blocat bogat',
  P2279: 'Scurgere aer admisie (aer fals)', P2290: 'Presiune control injectoare prea mică',
  P2300: 'Bobină aprindere A – primar scăzut', P2301: 'Bobină aprindere A – primar ridicat', P2303: 'Bobină aprindere B – primar scăzut',
  P2304: 'Bobină aprindere B – primar ridicat', P2306: 'Bobină aprindere C – primar scăzut', P2307: 'Bobină aprindere C – primar ridicat',
  P2309: 'Bobină aprindere D – primar scăzut', P2310: 'Bobină aprindere D – primar ridicat',
  P2400: 'Pompă detecție scurgeri EVAP – circuit', P2401: 'Pompă detecție scurgeri EVAP – scăzut',
  P2413: 'Sistem EGR – performanță', P2425: 'Supapă răcire EGR – circuit deschis', P2426: 'Supapă răcire EGR – scăzut',
  P242F: 'Filtru particule (DPF) – restricție / acumulare cenușă', P2452: 'Senzor presiune diferențială DPF – circuit',
  P2453: 'Senzor presiune diferențială DPF – domeniu/performanță', P2454: 'Senzor presiune DPF – semnal scăzut',
  P2455: 'Senzor presiune DPF – semnal ridicat', P2458: 'Durată regenerare DPF', P2459: 'Frecvență regenerare DPF excesivă',
  P2463: 'Filtru particule (DPF) – acumulare funingine excesivă', P2502: 'Tensiune încărcare alternator',
  P2503: 'Tensiune încărcare scăzută', P2504: 'Tensiune încărcare ridicată', P2507: 'Alimentare ECM/PCM B scăzută',
  P2509: 'Alimentare ECM/PCM intermitentă', P2610: 'Temporizator oprire motor ECM/PCM – performanță',
  P2626: 'Sondă O2 B1S1 – circuit compensare deschis',
  /* ---------- Ford P1xxx (specifice producător) ---------- */
  P1000: 'Ford: monitoare OBD-II incomplete (după ștergerea codurilor / deconectare baterie) – informativ',
  P1001: 'Ford: test KOER (motor pornit) nu a putut fi finalizat', P1100: 'Ford: senzor MAF – intermitent',
  P1101: 'Ford: senzor MAF în afara domeniului autotestului', P1112: 'Ford: senzor IAT – intermitent',
  P1116: 'Ford: senzor ECT în afara domeniului autotestului', P1117: 'Ford: senzor ECT – intermitent',
  P1120: 'Ford: senzor poziție clapetă în afara domeniului (scăzut)', P1121: 'Ford: TP inconsistent cu MAF',
  P1124: 'Ford: senzor poziție clapetă în afara domeniului autotestului', P1125: 'Ford: senzor TP – intermitent',
  P1127: 'Ford: evacuare nu e caldă – teste încălzire sondă O2 aval incomplete',
  P1130: 'Ford: lipsă comutare sondă O2 B1S1 – corecție la limită', P1131: 'Ford: lipsă comutare sondă O2 B1S1 – indică amestec sărac',
  P1132: 'Ford: lipsă comutare sondă O2 B1S1 – indică amestec bogat', P1137: 'Ford: lipsă comutare sondă O2 B1S2 – indică sărac',
  P1138: 'Ford: lipsă comutare sondă O2 B1S2 – indică bogat', P1150: 'Ford: lipsă comutare sondă O2 B2S1 – corecție la limită',
  P1151: 'Ford: lipsă comutare sondă O2 B2S1 – indică sărac', P1152: 'Ford: lipsă comutare sondă O2 B2S1 – indică bogat',
  P1168: 'Ford: senzor presiune rampă combustibil în afara domeniului', P1169: 'Ford: senzor presiune rampă – fără variație',
  P1180: 'Ford: sistem livrare combustibil – scăzut', P1181: 'Ford: sistem livrare combustibil – ridicat',
  P1220: 'Ford: sistem control clapetă – serie', P1224: 'Ford: senzor poziție clapetă B în afara domeniului autotestului',
  P1229: 'Ford: răcitor intermediar (intercooler) pompă – circuit', P1233: 'Ford: modul control pompă combustibil (FPDM) – dezactivat/offline',
  P1235: 'Ford: pompă combustibil – control în afara domeniului', P1237: 'Ford: pompă combustibil – circuit secundar',
  P1260: 'Ford: FURT detectat – motor imobilizat (PATS)', P1270: 'Ford: limitator turație/viteză motor atins',
  P1285: 'Ford: supratemperatură chiulasă detectată', P1288: 'Ford: senzor temperatură chiulasă (CHT) în afara domeniului',
  P1289: 'Ford: senzor CHT – semnal ridicat', P1290: 'Ford: senzor CHT – semnal scăzut', P1299: 'Ford: protecție supratemperatură chiulasă activă (FMEM)',
  P1309: 'Ford: monitor rateuri – AICE neînvățat', P1336: 'Ford: senzor poziție arbore cotit/came – domeniu/performanță',
  P1351: 'Ford: semnal diagnoză aprindere (IDM) – circuit intrare', P1380: 'Ford: solenoid VCT – circuit',
  P1381: 'Ford: sincronizare VCT prea avansată', P1383: 'Ford: sincronizare VCT prea întârziată',
  P1390: 'Ford: corecție octanică (OAR) în afara domeniului', P1397: 'Ford: tensiune sistem în afara domeniului autotestului',
  P1400: 'Ford: senzor DPFE (EGR) – semnal scăzut', P1401: 'Ford: senzor DPFE (EGR) – semnal ridicat',
  P1405: 'Ford: senzor DPFE – furtun amonte deconectat/înfundat', P1406: 'Ford: senzor DPFE – furtun aval deconectat/înfundat',
  P1408: 'Ford: debit EGR în afara domeniului autotestului', P1409: 'Ford: regulator vacuum EGR (EVR) – circuit',
  P1411: 'Ford: aer secundar – debit aval incorect', P1413: 'Ford: monitor aer secundar – circuit scăzut',
  P1443: 'Ford: EVAP – sistem control debit purjare', P1450: 'Ford: imposibil de creat vacuum în rezervor (EVAP)',
  P1451: 'Ford: supapă aerisire canistră EVAP – circuit', P1460: 'Ford: releu întrerupere A/C la accelerație maximă (WOT) – circuit',
  P1464: 'Ford: cerere A/C în afara domeniului autotestului', P1474: 'Ford: ventilator răcire – circuit control primar',
  P1479: 'Ford: ventilator răcire viteză mare – circuit', P1500: 'Ford: senzor viteză vehicul – intermitent',
  P1501: 'Ford: senzor viteză vehicul în afara domeniului autotestului', P1504: 'Ford: supapă aer ralanti (IAC) – circuit',
  P1506: 'Ford: supapă IAC – supraturație (overspeed)', P1507: 'Ford: supapă IAC – subturație (underspeed)',
  P1516: 'Ford: IMRC – bancul 1, poziție incorectă', P1517: 'Ford: IMRC – bancul 2, poziție incorectă',
  P1518: 'Ford: IMRC – defect deschis', P1519: 'Ford: IMRC – defect închis', P1520: 'Ford: IMRC – circuit',
  P1549: 'Ford: supapă/solenoid admisie (IMTV) – circuit', P1550: 'Ford: senzor presiune servodirecție (PSP) în afara domeniului',
  P1572: 'Ford: comutator pedală frână – circuit', P1575: 'Ford: pedală accelerație – semnal în afara domeniului',
  P1576: 'Ford: pedală accelerație – semnal nedisponibil', P1578: 'Ford: sistem control electronic clapetă (ETC) – putere sub cerere',
  P1605: 'Ford: memorie KAM PCM – test eșuat (baterie deconectată?)', P1625: 'Ford: alimentare B+ releu ventilator – circuit',
  P1626: 'Ford: alimentare B+ releu ventilator 2 – circuit', P1633: 'Ford: tensiune KAM prea mică',
  P1635: 'Ford: raport anvelope/punte în afara domeniului acceptabil', P1636: 'Ford: eroare comunicație cip semnătură inductivă (transmisie)',
  P1639: 'Ford: bloc ID vehicul (VID) neprogramat sau corupt', P1640: 'Ford: DTC-uri disponibile în alt modul (citiți modulele)',
  P1650: 'Ford: comutator presiune servodirecție în afara domeniului', P1651: 'Ford: comutator presiune servodirecție – intrare',
  P1700: 'Ford: transmisie – defect neidentificat', P1702: 'Ford: senzor domeniu transmisie (TRS) – intermitent',
  P1703: 'Ford: comutator frână în afara domeniului autotestului', P1705: 'Ford: TRS nu e în P/N în timpul autotestului',
  P1711: 'Ford: senzor TFT în afara domeniului autotestului', P1744: 'Ford: solenoid TCC – performanță',
  P1746: 'Ford: solenoid EPC – circuit deschis', P1747: 'Ford: solenoid EPC – scurtcircuit', P1749: 'Ford: solenoid EPC – defect scăzut',
  P1780: 'Ford: comutator control transmisie (O/D) în afara domeniului autotestului', P1781: 'Ford: comutator 4x4 Low în afara domeniului',
  P1783: 'Ford: supratemperatură transmisie', P1900: 'Ford: senzor OSS – intermitent', P1901: 'Ford: senzor turbină (TSS) – intermitent',
  /* ---------- Rețea (U) ---------- */
  U0001: 'Magistrală CAN viteză mare (HS-CAN) – defect', U0010: 'Magistrală CAN viteză medie (MS-CAN) – defect',
  U0073: 'Magistrală comunicație modul A – bus off', U0100: 'Pierdere comunicație cu ECM/PCM', U0101: 'Pierdere comunicație cu TCM',
  U0102: 'Pierdere comunicație cu modulul transfer (4x4)', U0121: 'Pierdere comunicație cu ABS', U0131: 'Pierdere comunicație cu servodirecția (PSCM)',
  U0140: 'Pierdere comunicație cu BCM/GEM', U0151: 'Pierdere comunicație cu modulul airbag (RCM)', U0155: 'Pierdere comunicație cu bordul (IPC)',
  U0159: 'Pierdere comunicație cu asistența parcare (PAM)', U0164: 'Pierdere comunicație cu climatizarea (HVAC)',
  U0184: 'Pierdere comunicație cu radio/audio', U0197: 'Pierdere comunicație cu modulul telefon/SYNC', U0198: 'Pierdere comunicație cu modulul telematic',
  U0199: 'Pierdere comunicație cu modulul ușă A', U0200: 'Pierdere comunicație cu modulul ușă B', U0212: 'Pierdere comunicație cu SCCM',
  U0214: 'Pierdere comunicație cu modulul acces fără cheie', U0253: 'Pierdere comunicație cu modulul acces fără cheie',
  U0256: 'Pierdere comunicație cu FCIM', U0300: 'Incompatibilitate software modul intern',
  U0401: 'Date invalide primite de la ECM/PCM', U0402: 'Date invalide primite de la TCM', U0415: 'Date invalide primite de la ABS',
  U0422: 'Date invalide primite de la BCM/GEM', U0423: 'Date invalide primite de la bord (IPC)', U0428: 'Date invalide de la senzorul unghi volan',
  U0452: 'Date invalide primite de la RCM', U1000: 'Ford: magistrală comunicație SCP/CAN – lipsă mesaje (defect rețea)',
  U1900: 'Ford: comunicație CAN – eroare recepție', U2023: 'Ford: defect raportat de alt modul',
  U2100: 'Ford: configurație inițială CAN incompletă', U2101: 'Ford: configurație control modul incompatibilă',
  U2200: 'Ford: configurație modul nevalidă / lipsă', U3000: 'Ford: modul de control – defect intern', U3003: 'Ford: tensiune baterie',
  /* ---------- Caroserie (B) Ford ---------- */
  B1201: 'Ford: senzor nivel combustibil – defect circuit', B1202: 'Ford: senzor nivel combustibil – circuit deschis',
  B1204: 'Ford: senzor nivel combustibil – scurt la masă',
  B1317: 'Ford: tensiune baterie ridicată', B1318: 'Ford: tensiune baterie scăzută', B1342: 'Ford: modul defect intern (ECU defect)',
  B1352: 'Ford: contact cheie (ignition key-in) – circuit', B1359: 'Ford: contact (RUN/ACC) – circuit',
  B1600: 'Ford PATS: semnal transponder cheie nerecepționat', B1601: 'Ford PATS: format cheie invalid',
  B1602: 'Ford PATS: cheie – date incomplete', B1681: 'Ford PATS: semnal transceiver nerecepționat',
  B1676: 'Ford: tensiune baterie în afara domeniului', B1869: 'Ford: lampă airbag – circuit deschis',
  B1870: 'Ford: lampă airbag – scurt la baterie', B1884: 'Ford: lampă dezactivare airbag pasager (PAD) – circuit', B2477: 'Ford: configurație modul eșuată (As-Built)',
  B2431: 'Ford PATS: programare transponder eșuată',
  B1000: 'Ford: ECU defect intern',
  /* ---------- Șasiu (C) Ford ABS/ESP ---------- */
  C1095: 'Ford ABS: motor pompă hidraulică – circuit',
  C1145: 'Ford ABS: senzor turație roată dreapta-față – circuit intrare', C1155: 'Ford ABS: senzor turație roată stânga-față – circuit intrare',
  C1165: 'Ford ABS: senzor turație roată dreapta-spate – circuit intrare', C1175: 'Ford ABS: senzor turație roată stânga-spate – circuit intrare',
  C1185: 'Ford ABS: alimentare releu ABS – circuit', C1233: 'Ford ABS: semnal turație roată stânga-față lipsă',
  C1234: 'Ford ABS: semnal turație roată dreapta-față lipsă', C1235: 'Ford ABS: semnal turație roată dreapta-spate lipsă',
  C1236: 'Ford ABS: semnal turație roată stânga-spate lipsă', C1277: 'Ford: senzor unghi volan – circuit',
  C1280: 'Ford ESP: senzor rată girație – circuit',
  C1288: 'Ford ABS: senzor presiune circuit primar – circuit',
  C1446: 'Ford: comutator lumini frână – circuit', C1991: 'Ford: modul ABS – eroare calibrare',
};

/* completări generice SAE J2012 */
Object.assign(DTC_DB, {
  P0021: 'Ax came admisie – sincronizare prea avansată, bancul 2', P0022: 'Ax came admisie – sincronizare prea întârziată, bancul 2',
  P0023: 'Actuator ax came evacuare – circuit, bancul 2', P0024: 'Ax came evacuare – prea avansat, bancul 2', P0025: 'Ax came evacuare – prea întârziat, bancul 2',
  P0018: 'Corelație arbore cotit / ax came (bancul 2, senzor A)', P0019: 'Corelație arbore cotit / ax came (bancul 2, senzor B)',
  P0033: 'Supapă bypass turbo – circuit control', P0034: 'Supapă bypass turbo – circuit scăzut', P0035: 'Supapă bypass turbo – circuit ridicat',
  P0047: 'Solenoid control presiune turbo – circuit scăzut', P0048: 'Solenoid control presiune turbo – circuit ridicat',
  P0042: 'Încălzire sondă O2 – circuit control (B1S3)', P0051: 'Încălzire sondă O2 – nivel scăzut (B2S1)', P0052: 'Încălzire sondă O2 – nivel ridicat (B2S1)',
  P0056: 'Încălzire sondă O2 – circuit control (B2S2)', P0057: 'Încălzire sondă O2 – nivel scăzut (B2S2)', P0058: 'Încălzire sondă O2 – nivel ridicat (B2S2)',
  P0097: 'Senzor temperatură aer admisie 2 – semnal scăzut', P0098: 'Senzor temperatură aer admisie 2 – semnal ridicat',
  P0114: 'Senzor IAT – circuit intermitent', P0124: 'Senzor poziție clapetă A – intermitent', P0126: 'Temperatură lichid răcire insuficientă pentru funcționare stabilă',
  P0157: 'Sondă O2 B2S2 – tensiune scăzută', P0158: 'Sondă O2 B2S2 – tensiune ridicată', P0159: 'Sondă O2 B2S2 – răspuns lent', P0160: 'Sondă O2 B2S2 – fără activitate',
  P0182: 'Senzor temperatură combustibil A – semnal scăzut', P0183: 'Senzor temperatură combustibil A – semnal ridicat',
  P0194: 'Senzor presiune rampă – intermitent', P0213: 'Injector pornire la rece 1 – circuit', P0216: 'Sincronizare injecție – circuit control',
  P0225: 'Senzor poziție clapetă/pedală C – circuit', P0226: 'Senzor poziție C – domeniu/performanță', P0227: 'Senzor poziție C – semnal scăzut', P0228: 'Senzor poziție C – semnal ridicat',
  P0273: 'Injector cil. 5 – circuit scăzut', P0274: 'Injector cil. 5 – circuit ridicat', P0276: 'Injector cil. 6 – circuit scăzut', P0277: 'Injector cil. 6 – circuit ridicat',
  P0279: 'Injector cil. 7 – circuit scăzut', P0280: 'Injector cil. 7 – circuit ridicat', P0282: 'Injector cil. 8 – circuit scăzut', P0283: 'Injector cil. 8 – circuit ridicat',
  P0309: 'Rateuri cilindru 9', P0310: 'Rateuri cilindru 10', P0313: 'Rateuri detectate cu nivel scăzut de combustibil', P0314: 'Rateuri pe un singur cilindru (nespecificat)',
  P0331: 'Senzor detonație 2 – domeniu/performanță', P0332: 'Senzor detonație 2 – semnal scăzut', P0333: 'Senzor detonație 2 – semnal ridicat',
  P0346: 'Senzor CMP A – domeniu/performanță (bancul 2)', P0347: 'Senzor CMP A – semnal scăzut (bancul 2)', P0348: 'Senzor CMP A – semnal ridicat (bancul 2)',
  P0357: 'Bobină aprindere G – circuit', P0358: 'Bobină aprindere H – circuit', P0367: 'Senzor ax came B – semnal scăzut', P0368: 'Senzor ax came B – semnal ridicat',
  P0390: 'Senzor ax came B – circuit (bancul 2)', P0383: 'Modul bujii incandescente – circuit scăzut', P0384: 'Modul bujii incandescente – circuit ridicat',
  P0407: 'Senzor poziție EGR B – semnal scăzut', P0408: 'Senzor poziție EGR B – semnal ridicat', P0413: 'Supapă comutare aer secundar A – circuit deschis',
  P0414: 'Supapă comutare aer secundar A – scurtcircuit', P0418: 'Releu pompă aer secundar A – circuit', P0422: 'Eficiență catalizator principal sub prag – bancul 1',
  P0432: 'Eficiență catalizator principal sub prag – bancul 2', P0449: 'Supapă aerisire EVAP – circuit', P0450: 'Senzor presiune EVAP – circuit',
  P0454: 'Senzor presiune EVAP – intermitent', P0464: 'Senzor nivel combustibil – intermitent', P0475: 'Supapă control presiune evacuare – circuit',
  P0476: 'Supapă control presiune evacuare – domeniu/performanță', P0477: 'Supapă control presiune evacuare – scăzut', P0478: 'Supapă control presiune evacuare – ridicat',
  P0483: 'Ventilator răcire – verificare raționalitate', P0498: 'Supapă aerisire EVAP – circuit scăzut', P0499: 'Supapă aerisire EVAP – circuit ridicat',
  P0504: 'Corelație comutator frână A/B', P0508: 'Supapă aer ralanti – circuit scăzut', P0509: 'Supapă aer ralanti – circuit ridicat',
  P0531: 'Senzor presiune A/C – domeniu/performanță', P0544: 'Senzor temperatură gaze evacuare B1S1 – circuit', P0545: 'Senzor temperatură gaze evacuare B1S1 – scăzut',
  P0546: 'Senzor temperatură gaze evacuare B1S1 – ridicat', P0551: 'Senzor presiune servodirecție – domeniu/performanță', P0552: 'Senzor presiune servodirecție – scăzut',
  P0553: 'Senzor presiune servodirecție – ridicat', P0565: 'Cruise control – semnal ON', P0566: 'Cruise control – semnal OFF', P0567: 'Cruise control – semnal RESUME',
  P0568: 'Cruise control – semnal SET', P0569: 'Cruise control – semnal COAST', P0570: 'Cruise control – semnal ACCEL', P0597: 'Termostat încălzit – circuit control deschis',
  P0598: 'Termostat încălzit – circuit scăzut', P0599: 'Termostat încălzit – circuit ridicat', P0611: 'Modul control injectoare – performanță',
  P0616: 'Releu demaror – circuit scăzut', P0617: 'Releu demaror – circuit ridicat', P0634: 'Temperatură internă PCM/ECM/TCM prea mare',
  P0639: 'Actuator clapetă – domeniu/performanță (bancul 2)', P0644: 'Comunicație afișaj șofer – serial', P0646: 'Releu ambreiaj A/C – circuit scăzut',
  P0647: 'Releu ambreiaj A/C – circuit ridicat', P0654: 'Ieșire turație motor (turometru) – circuit', P0656: 'Ieșire nivel combustibil – circuit',
  P0658: 'Alimentare actuatori A – scăzut', P0659: 'Alimentare actuatori A – ridicat', P0675: 'Bujie incandescentă cilindru 5 – circuit', P0676: 'Bujie incandescentă cilindru 6 – circuit',
  P0688: 'Releu alimentare ECM/PCM – circuit sens deschis', P0698: 'Tensiune referință senzori C – scăzută', P0699: 'Tensiune referință senzori C – ridicată',
  P0703: 'Comutator frână B (transmisie) – circuit', P0709: 'Senzor domeniu transmisie – intermitent', P0714: 'Senzor TFT – intermitent',
  P0719: 'Comutator frână B – scăzut', P0724: 'Comutator frână B – ridicat', P0726: 'Intrare turație motor (TCM) – domeniu/performanță',
  P0727: 'Intrare turație motor (TCM) – fără semnal', P0744: 'TCC – intermitent', P0747: 'Solenoid presiune A – blocat cuplat', P0752: 'Solenoid schimbare A – blocat cuplat',
  P0757: 'Solenoid schimbare B – blocat cuplat', P0762: 'Solenoid schimbare C – blocat cuplat', P0766: 'Solenoid schimbare D – performanță', P0768: 'Solenoid schimbare D – electric',
  P0771: 'Solenoid schimbare E – performanță', P0773: 'Solenoid schimbare E – electric', P0785: 'Solenoid sincronizare schimbare – circuit',
  P0793: 'Senzor turație arbore intermediar – fără semnal', P0796: 'Solenoid control presiune C – performanță',
  P1407: 'Ford: EGR – lipsă debit detectată', P1442: 'Ford: EVAP – scurgere mică detectată', P1455: 'Ford: EVAP – scurgere mare / bușon (US)',
  P1474: 'Ford: ventilator răcire – circuit control primar',
  P1517: 'Ford: IMRC – bancul 2, poziție incorectă', P1537: 'Ford: IMRC – bancul 1 blocat deschis', P1538: 'Ford: IMRC – bancul 2 blocat deschis',
  P1550: 'Ford: senzor presiune servodirecție în afara domeniului', P1709: 'Ford: comutator PNP (park/neutral) în afara domeniului',
  P1714: 'Ford: solenoid schimbare A – defect inductiv', P1715: 'Ford: solenoid schimbare B – defect inductiv', P1728: 'Ford: patinare transmisie detectată',
  P1729: 'Ford: comutator 4x4 Low – defect', P1740: 'Ford: TCC – defect inductiv', P1741: 'Ford: TCC – eroare control', P1742: 'Ford: TCC – blocat cuplat',
  P1743: 'Ford: TCC – blocat cuplat (lumină TCIL)', P1754: 'Ford: solenoid control ambreiaj coast – circuit', P1760: 'Ford: solenoid EPC – scurt intermitent',
  P1779: 'Ford: lampă TCIL – circuit',
  U0002: 'Magistrală CAN viteză mare – performanță', U0011: 'Magistrală CAN viteză medie – performanță', U0103: 'Pierdere comunicație cu modulul schimbătorului de viteze',
  U0126: 'Pierdere comunicație cu senzorul unghi volan', U0132: 'Pierdere comunicație cu modulul suspensie', U0136: 'Pierdere comunicație cu modulul diferențial',
  U0141: 'Pierdere comunicație cu BCM A', U0146: 'Pierdere comunicație cu gateway A', U0167: 'Pierdere comunicație cu imobilizatorul',
  U0168: 'Pierdere comunicație cu modulul securitate vehicul', U0230: 'Pierdere comunicație cu modulul hayon/portbagaj', U0235: 'Pierdere comunicație cu senzorul cruise (ACC)',
  B1203: 'Ford: senzor nivel combustibil – scurt la baterie', B1213: 'Ford: număr chei programate insuficient (PATS)',
  B2141: 'Ford: date configurare NVM – eroare', B2139: 'Ford: date ID (PATS) – nepotrivire PCM/bord', B2103: 'Ford: antenă PATS – circuit',
});

const DTC_CATEGORY ={ P: 'Motor/transmisie (Powertrain)', C: 'Șasiu (Chassis)', B: 'Caroserie (Body)', U: 'Rețea comunicații (Network)' };

function describeDTC(code) {
  const c = code.toUpperCase();
  if (DTC_DB[c]) return DTC_DB[c];
  const L = c[0], d1 = c[1];
  const generic = (L === 'P' && (d1 === '0' || d1 === '2' || (d1 === '3' && c[2] >= '4'))) || (L !== 'P' && d1 === '0');
  return (generic ? 'Cod generic ' : 'Cod specific producător ') + '(' + (DTC_CATEGORY[L] || '') + ') — descriere indisponibilă în baza locală';
}

function dtcSeverity(code) {
  const c = code.toUpperCase();
  if (/^P03\d\d/.test(c) || /^P021[7-9]/.test(c) || /^P052[0-4]/.test(c) || c === 'P1285' || c === 'P1299' || /^P01[12]/.test(c) && c.endsWith('8') || /^C1/.test(c) || /^B19/.test(c)) return 'ridicată';
  if (/^P04[2-5]/.test(c) || c === 'P1000' || /^P044/.test(c) || /^P045/.test(c) || /^U3003/.test(c)) return 'scăzută';
  return 'medie';
}

window.describeDTC = describeDTC;
window.dtcSeverity = dtcSeverity;
window.DTC_DB = DTC_DB;
